# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWxL_Ue0IJSWHKRroOAKUz1tHpd7gggu
"""

# Exercicio 01

def max_consecutive_sum(lista):
    max_sum = lista[0]
    current_sum = lista[0]

    for i in range(1, len(lista)):
        current_sum += lista[i]


        if lista[i] > current_sum:
          current_sum = lista[i]

        if current_sum > max_sum:
            max_sum = current_sum

    return max_sum

# Testando a função
lista1 = [1, -3, 2, 1, -1] #3
lista2 = [-2, 1, -3, 4, -1, 2, 1, -5, 4] #6
lista3 = [5, -1, -2, 3, -1, 2, -4] #7
lista4 = [1] #1
lista5 = [-1, -2, -3, -4, -5] # -1

print("Maior soma consecutiva da lista 1:", max_consecutive_sum(lista1))

#exercício 2


def is_palindrome(string):
    string = string.replace(" ", "").lower()

    if string == string[::-1]:
        return True
    else:
        return False



print(is_palindrome("radar"))
print(is_palindrome("Python"))
print(is_palindrome("Ana"))

def contar_subconjuntos_crescentes(numeros):
    total = 0

    for i in range(len(numeros)):
        subconjunto = [numeros[i]]

        for j in range(i + 1, len(numeros)):
            if numeros[j] > subconjunto[-1]:
                subconjunto.append(numeros[j])
                total += 1

        total += 1

    return total

numeros = [1, 3, 2, 4]
print("Número total de subconjuntos crescentes:", contar_subconjuntos_crescentes(numeros))